```{r table5, include=FALSE}

c11 <- nrow(df[which(df$has_lib == "1"),])
c21 <- sum(as.numeric(df$total_items), na.rm = TRUE)
c31 <- nrow(df[which(df$bld_owner == "moe"),])
c41 <- nrow(df[which(df$bld_owner == "gov_oth"),])
c51 <- nrow(df[which(df$bld_owner == "rent"),])
c61 <- nrow(df[which(df$bld_cond == "ok"),])
c71 <- nrow(df[which(df$bld_cond == "rep"),])
c81 <- nrow(df[which(df$bld_cond == "nok"),])
c91 <- nrow(df[which(df$bld_material == "brk"),])
c101 <- nrow(df[which(df$bld_material == "pre"),])
c111 <- nrow(df[df$bld_material == "mud" | df$bld_material == "hut", ])
c121 <- nrow(df[which(df$qbld_material == "stl"),])
c121 <- nrow(df[which(df$bld_material == "car"),])
c131 <- nrow(df[which(df$bld_material == "oth"),])
```

```{=latex}
\begin{table}[H]
\centering
\Large
\caption[]{عدد الأبنية والمكتبات}
\renewcommand{\arraystretch}{1.6}
\begin{tabular}{|c|c|ccc|ccc|cccccc|}
\hline
عدد   المكتبات المدرسية       & \multirow{3}{*}{عدد الكتب} & \multicolumn{3}{c|}{عدد الأبنية   حسب العائدية}                                                    & \multicolumn{3}{c|}{عدد الأبنية حسب الحالة العمرانية}                                                                                                                      & \multicolumn{6}{c|}{عدد الأبنية حسب مادة البناء}                                                                                                                                                                                                                                                                               \\ \cline{1-1} \cline{3-14} 
\multirow{2}{*}{عدد المكتبات} &                            & \multicolumn{2}{c|}{حكومية}                                             & \multirow{2}{*}{مستأجرة} & \multicolumn{1}{c|}{\multirow{2}{*}{صالحة}} & \multicolumn{1}{c|}{\multirow{2}{*}{بحاجة إلى ترميم}} & \multirow{2}{*}{\begin{tabular}[c]{@{}c@{}}غير\\ صالحة\end{tabular}} & \multicolumn{1}{c|}{\multirow{2}{*}{\begin{tabular}[c]{@{}c@{}}طابوق\\ أو حجر\end{tabular}}} & \multicolumn{1}{c|}{\multirow{2}{*}{بناء جاهز}} & \multicolumn{1}{c|}{\multirow{2}{*}{طين او صريفة}} & \multicolumn{1}{c|}{\multirow{2}{*}{هياكل حديدية}} & \multicolumn{1}{c|}{\multirow{2}{*}{كرفان}} & \multirow{2}{*}{أخرى} \\ \cline{3-4}
                              &                            & \multicolumn{1}{c|}{عائدة   للتربية} & \multicolumn{1}{c|}{لجهات أخرى}  &                          & \multicolumn{1}{c|}{}                       & \multicolumn{1}{c|}{}                                 &                                                                      & \multicolumn{1}{c|}{}                                                                        & \multicolumn{1}{c|}{}                           & \multicolumn{1}{c|}{}                              & \multicolumn{1}{c|}{}                              & \multicolumn{1}{c|}{}                       &                       \\ \hline
`r ad(c11)`                   & `r ad(c21)`                & \multicolumn{1}{c|}{`r ad(c31)`}     & \multicolumn{1}{c|}{`r ad(c41)`} & `r ad(c51)`              & \multicolumn{1}{c|}{`r ad(c61)`}            & \multicolumn{1}{c|}{`r ad(c71)`}                      & `r ad(c81)`                                                          & \multicolumn{1}{c|}{`r ad(c91)`}                                                             & \multicolumn{1}{c|}{`r ad(c101)`}               & \multicolumn{1}{c|}{`r ad(c111)`}                  & \multicolumn{1}{c|}{`r ad(c121)`}                  & \multicolumn{1}{c|}{`r ad(c131)`}           & `r ad(c141)`          \\ \hline
\end{tabular}%
\end{table}
```
```{r table5_1, include=FALSE}
c11 <- nrow(df[which(df$bld_type == "sch"),])
c21 <- nrow(df[which(df$bld_type == "non_sch"),])

c31 <- nrow(df[which(df$occupancy == "sgl"),])
c41 <- nrow(df[which(df$occupancy == "dbl"),])
c51 <- nrow(df[which(df$occupancy == "multi"),])
c61 <- c31 + c41 + c51

c71 <- nrow(df[which(df$has_san == "1"),])
c81 <- nrow(df[which(df$drink_water == "1"),])
c91 <- nrow(df[which(df$has_sewer == "1"),])
c101<- nrow(df[which(df$has_fence == "1"),])
```

```{=latex}
\begin{table}[H]
\centering
\Large
\caption*{جدول ٥-١: عدد الابنية المدرسية ونوع لخدمات}
\renewcommand{\arraystretch}{1.6}
\begin{tabular}{|cc|ccc|c|cccc|}
\hline
\multicolumn{2}{|c|}{عدد الأبنية حسب نوعها}     & \multicolumn{3}{c|}{عدد الابنية التي تشغلها}                                      & \multirow{2}{*}{المجموع الكلي للابنية} & \multicolumn{4}{c|}{عدد الابنية حسب الخدمات}                                                                                                          \\ \cline{1-5} \cline{7-10} 
\multicolumn{1}{|c|}{مدرسي}       & غير مدرسي   & \multicolumn{1}{c|}{مدرسة واحدة} & \multicolumn{1}{c|}{مدرستان}     & ثلاث فاكثر  &                                        & \multicolumn{1}{c|}{تتوفر فيها مرافق صحية} & \multicolumn{1}{c|}{المزودة بخدمة ماء} & \multicolumn{1}{c|}{المزودة بخدمة مجاري} & تحتوي على سياج مدرسي \\ \hline
\multicolumn{1}{|c|}{`r ad(c11)`} & `r ad(c21)` & \multicolumn{1}{c|}{`r ad(c31)`} & \multicolumn{1}{c|}{`r ad(c41)`} & `r ad(c51)` & `r ad(c61)`                            & \multicolumn{1}{c|}{`r ad(c71)`}           & \multicolumn{1}{c|}{`r ad(c81)`}       & \multicolumn{1}{c|}{`r ad(c91)`}         & `r ad(c101)`         \\ \hline
\end{tabular}%
\end{table}
```
```{r table5_2, include=FALSE}
c11 <- nrow(df[which(df$floors == "f1"),])
c21 <- nrow(df[which(df$floors == "f2"),])
c31 <- nrow(df[which(df$floors == "f3"),])
c41 <- c11 + c21

c51 <- nrow(df[which(df$capacity == "c6"),])
c61 <- nrow(df[which(df$capacity == "c9"),])
c71 <- nrow(df[which(df$capacity == "c12"),])
c81 <- nrow(df[which(df$capacity == "c18"),])
c91 <- nrow(df[which(df$capacity == "c24"),])
c101 <- c51 + c61 + c71 + c81 + c91
```

```{=latex}
\begin{table}[H]
\centering
\Large
\caption*{جدول ٥-٢: عدد الابنية المدرسية حسب عدد الطوابق وعدد الصفوف}
\renewcommand{\arraystretch}{1.6}
\begin{tabular}{|cccc|cccccc|}
\hline
\multicolumn{4}{|c|}{عدد الابنية حسب عدد الطوابق}                                                                     & \multicolumn{6}{c|}{عدد الابنية حسب عدد الصفوف}                                                                                                                                                     \\ \hline
\multicolumn{1}{|c|}{طابق واحد}   & \multicolumn{1}{c|}{طابقين}      & \multicolumn{1}{c|}{ثلاثة طوابق} & المجموع     & \multicolumn{1}{c|}{`r ad(6)` صف} & \multicolumn{1}{c|}{`r ad(9)` صف} & \multicolumn{1}{c|}{`r ad(12)` صف} & \multicolumn{1}{c|}{`r ad(18)` صف} & \multicolumn{1}{c|}{`r ad(24)` صف} & المجموع      \\ \hline
\multicolumn{1}{|c|}{`r ad(c11)`} & \multicolumn{1}{c|}{`r ad(c21)`} & \multicolumn{1}{c|}{`r ad(c31)`} & `r ad(c41)` & \multicolumn{1}{c|}{`r ad(c51)`}  & \multicolumn{1}{c|}{`r ad(c61)`}  & \multicolumn{1}{c|}{`r ad(c71)`}   & \multicolumn{1}{c|}{`r ad(c81)`}   & \multicolumn{1}{c|}{`r ad(c91)`}   & `r ad(c101)` \\ \hline
\end{tabular}%
\end{table}
```